### ISSUE TITLE
Yarn install on arm64 linux

### ISSUE THREAD

**Issue by ZerdoX-x** [owlbear-rodeo/kenku-fm#108]
1. Arm64 linux laptop (gentoo on asahi on m1 in my case)
2. `yarn install`
3. See error

**Expected behavior**
Proper installation of dependencies

**Logs**
```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@emotion/react > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > redux-persist@6.0.0" has unmet peer dependency "redux@>4.0.0".
warning " > css-loader@6.6.0" has unmet peer dependency "webpack@^5.0.0".
warning " > fork-ts-checker-webpack-plugin@7.2.1" has unmet peer dependency "webpack@^5.11.0".
warning " > node-loader@2.0.0" has unmet peer dependency "webpack@^5.0.0".
warning " > style-loader@3.3.1" has unmet peer dependency "webpack@^5.0.0".
warning " > ts-loader@9.2.6" has unmet peer dependency "webpack@^5.0.0".
warning " > worker-loader@3.0.8" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > worklet-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
[4/4] Building fresh packages...
[1/3] ⠐ lzma-native
[-/3] ⠐ waiting...
error /home/zerdox/downloads/kenku-fm/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /home/zerdox/downloads/kenku-fm/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v21.3.0+wvcus/electron-v21.3.0+wvcus-linux-arm64.zip
    at EventEmitter.<anonymous> (/home/zerdox/downloads/kenku-fm/node_modules/electron/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:514:28)
    at module.exports (/home/zerdox/downloads/kenku-fm/node_modules/electron/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/zerdox/downloads/kenku-fm/node_modules/electron/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (/home/zerdox/downloads/kenku-fm/node_modules/electron/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Desktop:**
 - OS: Gentoo Linux on M1 Laptop (asahi kernel 6.6.0)

**Comment by mitchemmc** [comment]
For linux arm you should use our linux-arm branch

**Comment by ZerdoX-x** [comment]
> For linux arm you should use our linux-arm branch

```
$ yarn make
yarn run v1.22.21
$ yarn --cwd ./severus build-release && electron-forge make
$ yarn build -- --release
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ cargo-cp-artifact -nc ../dist/index.node -- cargo build --message-format=json-render-diagnostics --release
/bin/sh: line 1: cargo-cp-artifact: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There is an unhandled devdependency. Could you isolate it so there is no need to install it globally?
